### ISSUE TITLE
Image policies are not triggerd via webhook receiver with image-reflector-controller v0.13.1

### ISSUE THREAD

**Issue by glen-uc** [fluxcd/image-reflector-controller#201] opened 2021-11-12 10:06 UTC
Description:

When we trigger a receiver configured for an image repository via webhooks, the image policy does not run hence latest image tag does not get applied to a workload via image automation

Steps to Reproduce:

In flux-system namespace:
  1. Create an Image Repo, Image Policy and Receiver CRD for an image (In our case ECR image) 
  2. Have image automation already configured for a git repo

In some other namespace:
  
1. Deploy and application referencing the image policy defined earlier in flux-system namespace
2. Push a new image to ECR and trigger the webhook configured for image receiver 

Expected Result:

The new image tag should get resolved in image policy and applied to the application via image automation

Actual result:

The new image tag was not resolved in the image policy

Note: After we delete the image controller new tags get resolved but if you repeat the above steps again new tags are not resolved until the next restart of image controller

```
flux: v0.22.1
helm-controller: v0.12.2
image-automation-controller: v0.17.1
image-reflector-controller: v0.13.1
kustomize-controller: v0.17.0
notification-controller: v0.18.1
source-controller: v0.17.2
```

Reverting to image-reflector-controller: v0.13.0 fixed the above issue

**Comment by hiddeco** [comment] 2021-11-12 10:12
Duplicate of #198, fixed in #199, available in `v0.13.2`: https://github.com/fluxcd/image-reflector-controller/releases/tag/v0.13.2

**Closed by hiddeco** 2021-11-12 10:12 UTC
